"""
Tests for src/game_logic.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.game_logic import *



# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def gamelogic_instance():
    """Fixture for GameLogic instance"""
    return GameLogic()



# ============================================================================
# Tests for __init__()
# ============================================================================

import pytest
from unittest.mock import patch
from src.game_logic import GameLogic


@patch('random.randint')
def test_init_default_values_and_state(mock_randint):
    """
    Test __init__ with default min_num and max_num,
    ensuring correct initial state and target number generation.
    """
    mock_randint.return_value = 50  # Mock target number for predictability
    game = GameLogic()

    assert game._min_num == 1
    assert game._max_num == 100
    assert game._attempts_made == 0
    assert game._game_over is False
    assert game._target_number == 50
    mock_randint.assert_called_once_with(1, 100)


@patch('random.randint')
def test_init_custom_valid_values(mock_randint):
    """
    Test __init__ with custom valid min_num and max_num,
    ensuring correct attribute assignment and target number generation.
    """
    mock_randint.return_value = 15  # Mock target number for predictability
    game = GameLogic(min_num=10, max_num=20)

    assert game._min_num == 10
    assert game._max_num == 20
    assert game._attempts_made == 0
    assert game._game_over is False
    assert game._target_number == 15
    mock_randint.assert_called_once_with(10, 20)


@patch('random.randint')
def test_init_min_equals_max(mock_randint):
    """
    Test __init__ when min_num is equal to max_num,
    an edge case where the target number must be that single value.
    """
    mock_randint.return_value = 75  # Should still be called, but the range is 75,75
    game = GameLogic(min_num=75, max_num=75)

    assert game._min_num == 75
    assert game._max_num == 75
    assert game._target_number == 75
    mock_randint.assert_called_once_with(75, 75)


def test_init_min_num_not_integer_raises_type_error():
    """
    Test __init__ raises TypeError when min_num is not an integer.
    """
    with pytest.raises(TypeError):
        GameLogic(min_num="1", max_num=100)


def test_init_max_num_not_integer_raises_type_error():
    """
    Test __init__ raises TypeError when max_num is not an integer.
    """
    with pytest.raises(TypeError):
        GameLogic(min_num=1, max_num="100")


def test_init_min_num_greater_than_max_num_raises_value_error():
    """
    Test __init__ raises ValueError when min_num is greater than max_num.
    """
    with pytest.raises(ValueError):
        GameLogic(min_num=100, max_num=1)


# ============================================================================
# Tests for reset_game()
# ============================================================================

import pytest
from unittest.mock import patch
from src.game_logic import GameLogic
import random

# Test 1: Verify that attempts_made and game_over flags are reset correctly.
def test_reset_game_resets_attempts_and_game_over(mocker):
    # Mock random.randint to return a predictable value for the target number.
    # This also allows us to verify that _generate_target_number is called.
    mock_randint = mocker.patch('random.randint', return_value=50)

    # Initialize GameLogic. __init__ calls reset_game, setting initial state.
    game = GameLogic(min_num=1, max_num=100)
    assert game.get_target_number() == 50
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()
    assert mock_randint.call_count == 1 # Called once by __init__

    # Simulate the game being played and completed
    game._attempts_made = 10
    game._game_over = True
    game._target_number = 75 # Change target to ensure it's reset later if not mocked

    # Call the reset_game method
    game.reset_game()

    # Assert that attempts_made is reset to 0
    assert game.get_attempts_made() == 0
    # Assert that game_over is reset to False
    assert not game.is_game_over()
    # Assert that _generate_target_number was called again (total 2 times)
    assert mock_randint.call_count == 2
    # The target number should be the value returned by the mock (still 50)
    assert game.get_target_number() == 50
    mock_randint.assert_called_with(game._min_num, game._max_num)


# Test 2: Verify that a new target number is generated within the correct range.
def test_reset_game_generates_new_target_number_within_range(mocker):
    # Mock random.randint to return different values for consecutive calls.
    # First call is from __init__, second from the explicit reset_game call.
    mock_randint = mocker.patch('random.randint', side_effect=[25, 75])

    game = GameLogic(min_num=1, max_num=100)

    # After initialization, the target number should be the first mocked value (25)
    assert game.get_target_number() == 25
    assert mock_randint.call_count == 1
    mock_randint.assert_called_with(1, 100) # Verify it was called with correct range

    game.reset_game()

    # After reset, the target number should be the second mocked value (75)
    assert game.get_target_number() == 75
    assert mock_randint.call_count == 2
    mock_randint.assert_called_with(1, 100) # Verify it was called again with correct range

    # Also verify that other states are reset
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()


# Test 3: Ensure game state is properly reset after a game has been "won".
def test_reset_game_after_game_over_by_winning(mocker):
    # Mock random.randint to ensure a predictable target for the first game.
    mock_randint_initial = mocker.patch('random.randint', return_value=50)
    
    game = GameLogic(min_num=1, max_num=100)
    assert game.get_target_number() == 50
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()
    mock_randint_initial.assert_called_once_with(1, 100)

    # Simulate playing and winning the game
    game.check_guess(10) # 1 attempt, Too low
    game.check_guess(80) # 2 attempts, Too high
    game.check_guess(50) # 3 attempts, Correct, game over

    assert game.get_attempts_made() == 3
    assert game.is_game_over()

    # Now, reset the game. Mock random.randint again for the reset operation.
    # This simulates a new target for the next game.
    mock_randint_reset = mocker.patch('random.randint', return_value=75)
    game.reset_game()

    # Verify that the game state is reset for a new game
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()
    assert game.get_target_number() == 75 # New target number after reset
    mock_randint_reset.assert_called_once_with(1, 100)


# Test 4: Resetting game with a custom range, ensuring target generation adheres to it.
def test_reset_game_with_custom_range(mocker):
    # Mock random.randint to return values specific to the custom range.
    mock_randint = mocker.patch('random.randint', side_effect=[5, 8])

    # Initialize GameLogic with a custom range (1-10)
    game = GameLogic(min_num=1, max_num=10)
    
    # After init, target should be 5, within 1-10
    assert game.get_target_number() == 5
    assert mock_randint.call_count == 1
    mock_randint.assert_called_with(1, 10) # Check generation within custom range

    # Reset the game
    game.reset_game()
    
    # After reset, target should be 8, also within 1-10
    assert game.get_target_number() == 8
    assert mock_randint.call_count == 2
    mock_randint.assert_called_with(1, 10) # Check generation within custom range again

    assert game.get_attempts_made() == 0
    assert not game.is_game_over()


# ============================================================================
# Tests for check_guess()
# ============================================================================

import pytest
from src.game_logic import GameLogic

# --- Happy Path Tests ---

def test_check_guess_too_low():
    """
    Test that check_guess correctly identifies a guess as "Too low".
    """
    game = GameLogic(1, 100)
    game.set_target_number(50)

    result = game.check_guess(40)
    assert result == "Too low"
    assert game.get_attempts_made() == 1
    assert not game.is_game_over()

def test_check_guess_too_high():
    """
    Test that check_guess correctly identifies a guess as "Too high".
    """
    game = GameLogic(1, 100)
    game.set_target_number(50)

    result = game.check_guess(60)
    assert result == "Too high"
    assert game.get_attempts_made() == 1
    assert not game.is_game_over()

def test_check_guess_correct():
    """
    Test that check_guess correctly identifies a guess as "Correct" and ends the game.
    """
    game = GameLogic(1, 100)
    game.set_target_number(50)

    result = game.check_guess(50)
    assert result == "Correct"
    assert game.get_attempts_made() == 1
    assert game.is_game_over()

def test_check_guess_multiple_attempts():
    """
    Test that attempts_made increments correctly over multiple guesses.
    """
    game = GameLogic(1, 100)
    game.set_target_number(75)

    game.check_guess(50) # Too low
    assert game.get_attempts_made() == 1
    assert not game.is_game_over()

    game.check_guess(90) # Too high
    assert game.get_attempts_made() == 2
    assert not game.is_game_over()

    game.check_guess(75) # Correct
    assert game.get_attempts_made() == 3
    assert game.is_game_over()

# --- Edge Case Tests ---

def test_check_guess_target_is_min_num():
    """
    Test guessing correctly when the target number is the minimum allowed number.
    """
    game = GameLogic(1, 10)
    game.set_target_number(1)

    result_low = game.check_guess(2)
    assert result_low == "Too high"
    assert game.get_attempts_made() == 1
    assert not game.is_game_over()
    game.reset_game() # Reset for a clean attempt

    game.set_target_number(1) # Re-set target after reset
    result_correct = game.check_guess(1)
    assert result_correct == "Correct"
    assert game.get_attempts_made() == 1
    assert game.is_game_over()

def test_check_guess_target_is_max_num():
    """
    Test guessing correctly when the target number is the maximum allowed number.
    """
    game = GameLogic(90, 100)
    game.set_target_number(100)

    result_high = game.check_guess(95)
    assert result_high == "Too low"
    assert game.get_attempts_made() == 1
    assert not game.is_game_over()
    game.reset_game() # Reset for a clean attempt

    game.set_target_number(100) # Re-set target after reset
    result_correct = game.check_guess(100)
    assert result_correct == "Correct"
    assert game.get_attempts_made() == 1
    assert game.is_game_over()

# --- Error Case Tests ---

def test_check_guess_type_error():
    """
    Test that check_guess raises TypeError for non-integer guesses.
    """
    game = GameLogic(1, 100)
    game.set_target_number(50)

    with pytest.raises(TypeError):
        game.check_guess(50.5)

    with pytest.raises(TypeError):
        game.check_guess("hello")

    # Ensure attempts and game_over state are not changed by invalid guess
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()

def test_check_guess_value_error_out_of_range_low():
    """
    Test that check_guess raises ValueError for guesses below the min_num.
    """
    game = GameLogic(10, 20)
    game.set_target_number(15)

    with pytest.raises(ValueError):
        game.check_guess(9)

    # Ensure attempts and game_over state are not changed by invalid guess
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()

def test_check_guess_value_error_out_of_range_high():
    """
    Test that check_guess raises ValueError for guesses above the max_num.
    """
    game = GameLogic(10, 20)
    game.set_target_number(15)

    with pytest.raises(ValueError):
        game.check_guess(21)

    # Ensure attempts and game_over state are not changed by invalid guess
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()

def test_check_guess_runtime_error_game_over():
    """
    Test that check_guess raises RuntimeError if called after the game is over.
    """
    game = GameLogic(1, 10)
    game.set_target_number(5)

    game.check_guess(5) # Correct guess, game ends
    assert game.is_game_over()

    with pytest.raises(RuntimeError):
        game.check_guess(3) # Attempt to guess again after game over

    # Attempts should remain at 1 after the correct guess
    assert game.get_attempts_made() == 1


# ============================================================================
# Tests for get_attempts_made()
# ============================================================================

import pytest
from src.game_logic import GameLogic
import random

# Use a fixed seed for random to make tests deterministic where applicable
# Although for get_attempts_made, the target number generation itself
# doesn't directly affect the count of attempts, just how many guesses
# it takes to win. We can set a specific target for easier testing.

@pytest.fixture
def game_instance():
    """Provides a fresh GameLogic instance for each test."""
    return GameLogic(1, 10) # Using a small range for easier testing

def test_get_attempts_made_initial_state(game_instance):
    """
    Test that get_attempts_made returns 0 immediately after game initialization.
    """
    assert game_instance.get_attempts_made() == 0

def test_get_attempts_made_after_one_guess(game_instance):
    """
    Test that get_attempts_made returns 1 after a single guess.
    """
    # Set a predictable target to avoid needing random.seed here
    game_instance.set_target_number(5)
    game_instance.check_guess(1) # Make a guess
    assert game_instance.get_attempts_made() == 1

def test_get_attempts_made_after_multiple_guesses(game_instance):
    """
    Test that get_attempts_made returns the correct count after multiple guesses.
    """
    game_instance.set_target_number(5)
    game_instance.check_guess(1) # 1st attempt
    game_instance.check_guess(2) # 2nd attempt
    game_instance.check_guess(3) # 3rd attempt
    assert game_instance.get_attempts_made() == 3

def test_get_attempts_made_after_game_over(game_instance):
    """
    Test that get_attempts_made returns the total attempts made to win.
    """
    game_instance.set_target_number(5)
    game_instance.check_guess(1) # 1st attempt
    game_instance.check_guess(8) # 2nd attempt
    game_instance.check_guess(5) # 3rd attempt, correct, game over
    assert game_instance.is_game_over() is True
    assert game_instance.get_attempts_made() == 3

def test_get_attempts_made_after_reset_game(game_instance):
    """
    Test that get_attempts_made resets to 0 after calling reset_game.
    """
    game_instance.set_target_number(5)
    game_instance.check_guess(1) # 1st attempt
    game_instance.check_guess(2) # 2nd attempt
    assert game_instance.get_attempts_made() == 2

    game_instance.reset_game() # Reset the game
    assert game_instance.get_attempts_made() == 0

def test_get_attempts_made_after_set_target_number(game_instance):
    """
    Test that get_attempts_made resets to 0 after calling set_target_number.
    """
    game_instance.set_target_number(5)
    game_instance.check_guess(1) # 1st attempt
    game_instance.check_guess(2) # 2nd attempt
    assert game_instance.get_attempts_made() == 2

    game_instance.set_target_number(7) # Setting a new target should reset attempts
    assert game_instance.get_attempts_made() == 0


# ============================================================================
# Tests for is_game_over()
# ============================================================================

import pytest
import random
from src.game_logic import GameLogic

# Suppress actual random number generation for predictable testing
@pytest.fixture(autouse=True)
def mock_random_randint(monkeypatch):
    """
    Fixture to mock random.randint to return a predictable value (e.g., 50)
    for target number generation, ensuring test determinism.
    """
    def mock_randint(a, b):
        return 50 # Always return 50 as the target number for testing
    monkeypatch.setattr(random, 'randint', mock_randint)


def test_is_game_over_initial_state():
    """
    Tests that is_game_over returns False immediately after game initialization.
    """
    game = GameLogic(1, 100)
    assert not game.is_game_over()

def test_is_game_over_after_incorrect_guess():
    """
    Tests that is_game_over returns False after one or more incorrect guesses.
    """
    game = GameLogic(1, 100) # Target will be 50 due to mock
    
    # Make an incorrect guess
    game.check_guess(25)
    assert not game.is_game_over()

    # Make another incorrect guess
    game.check_guess(75)
    assert not game.is_game_over()

def test_is_game_over_after_correct_guess():
    """
    Tests that is_game_over returns True after the correct number is guessed.
    """
    game = GameLogic(1, 100) # Target will be 50 due to mock
    
    # Make the correct guess
    game.check_guess(50)
    assert game.is_game_over()

def test_is_game_over_after_reset():
    """
    Tests that is_game_over returns False after the game is reset,
    even if it was previously over.
    """
    game = GameLogic(1, 100) # Target will be 50 due to mock
    
    # Make a correct guess to set game_over to True
    game.check_guess(50)
    assert game.is_game_over()

    # Reset the game
    game.reset_game()
    assert not game.is_game_over()


# ============================================================================
# Tests for get_range()
# ============================================================================

import pytest
from src.game_logic import GameLogic

def test_get_range_default_init():
    """
    Tests get_range with default min_num and max_num (1, 100).
    """
    game = GameLogic()
    expected_range = (1, 100)
    assert game.get_range() == expected_range

def test_get_range_custom_positive_init():
    """
    Tests get_range with custom positive min_num and max_num.
    """
    min_val = 10
    max_val = 50
    game = GameLogic(min_num=min_val, max_num=max_val)
    expected_range = (min_val, max_val)
    assert game.get_range() == expected_range

def test_get_range_negative_and_zero_init():
    """
    Tests get_range with negative and zero min_num and max_num.
    """
    min_val = -10
    max_val = 0
    game = GameLogic(min_num=min_val, max_num=max_val)
    expected_range = (min_val, max_val)
    assert game.get_range() == expected_range

def test_get_range_single_number_range():
    """
    Tests get_range when min_num and max_num are the same.
    """
    single_num = 7
    game = GameLogic(min_num=single_num, max_num=single_num)
    expected_range = (single_num, single_num)
    assert game.get_range() == expected_range


# ============================================================================
# Tests for get_target_number()
# ============================================================================

import pytest
from src.game_logic import GameLogic
import random

# Mock random.randint for predictable target generation in some tests
# We'll use this with monkeypatch to ensure specific outcomes.

def test_get_target_number_initial_default_range():
    """
    Test that get_target_number returns a number within the default range
    after initial game setup.
    """
    game = GameLogic()
    target = game.get_target_number()
    min_num, max_num = game.get_range() # Get the actual range from the instance
    assert isinstance(target, int)
    assert min_num <= target <= max_num # Should be 1 <= target <= 100

def test_get_target_number_initial_custom_range():
    """
    Test that get_target_number returns a number within a custom range
    after initial game setup.
    """
    custom_min, custom_max = 10, 20
    game = GameLogic(min_num=custom_min, max_num=custom_max)
    target = game.get_target_number()
    min_num, max_num = game.get_range()
    assert isinstance(target, int)
    assert min_num <= target <= max_num # Should be 10 <= target <= 20

def test_get_target_number_after_reset_game(monkeypatch):
    """
    Test that get_target_number returns a new number within range after reset_game,
    using monkeypatch to control random.randint for predictability.
    """
    # Simulate random.randint always returning 50 initially, then 75 after reset
    call_count = 0
    def mock_randint(a, b):
        nonlocal call_count
        call_count += 1
        if call_count == 1:
            return 50
        else:
            return 75

    monkeypatch.setattr(random, 'randint', mock_randint)

    game = GameLogic()
    initial_target = game.get_target_number()
    assert initial_target == 50 # Verifies the first call to mock_randint

    game.reset_game()
    new_target = game.get_target_number()
    assert new_target == 75 # Verifies the second call to mock_randint
    assert new_target != initial_target # Ensure it's a different number after reset

    min_num, max_num = game.get_range()
    assert min_num <= new_target <= max_num # Ensure it's still in range (1-100)

def test_get_target_number_after_set_target_number():
    """
    Test that get_target_number returns the explicitly set target number.
    """
    game = GameLogic()
    test_target_value = 55
    game.set_target_number(test_target_value)
    retrieved_target = game.get_target_number()
    assert retrieved_target == test_target_value

    # Verify that setting an extreme value within range works
    game.set_target_number(game._min_num)
    assert game.get_target_number() == game._min_num
    game.set_target_number(game._max_num)
    assert game.get_target_number() == game._max_num


# ============================================================================
# Tests for set_target_number()
# ============================================================================

import pytest
from src.game_logic import GameLogic

def test_set_target_number_happy_path():
    """
    Tests setting a valid target number within the default range.
    Ensures attempts are reset and game is not over.
    """
    game = GameLogic()
    # Initially, the target number is randomly set, attempts are 0, game_over is False
    # Let's make some attempts to change the state before setting a new target
    game.check_guess(game.get_range()[0]) # Make an attempt
    assert game.get_attempts_made() == 1

    new_target = 50
    game.set_target_number(new_target)

    assert game.get_target_number() == new_target
    assert game.get_attempts_made() == 0  # Should reset attempts
    assert not game.is_game_over()      # Should reset game_over state

def test_set_target_number_to_min_range_edge_case():
    """
    Tests setting the target number to the minimum allowed value in the range.
    """
    game = GameLogic(min_num=10, max_num=20)
    min_val = game.get_range()[0]
    game.set_target_number(min_val)

    assert game.get_target_number() == min_val
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()

def test_set_target_number_to_max_range_edge_case():
    """
    Tests setting the target number to the maximum allowed value in the range.
    """
    game = GameLogic(min_num=10, max_num=20)
    max_val = game.get_range()[1]
    game.set_target_number(max_val)

    assert game.get_target_number() == max_val
    assert game.get_attempts_made() == 0
    assert not game.is_game_over()

def test_set_target_number_type_error_non_integer():
    """
    Tests that a TypeError is raised when the target is not an integer.
    """
    game = GameLogic()
    with pytest.raises(TypeError):
        game.set_target_number(50.5)
    with pytest.raises(TypeError):
        game.set_target_number("invalid")
    with pytest.raises(TypeError):
        game.set_target_number(None)

def test_set_target_number_value_error_out_of_range():
    """
    Tests that a ValueError is raised when the target is outside the allowed range.
    """
    game = GameLogic(min_num=1, max_num=10)

    with pytest.raises(ValueError):
        game.set_target_number(0) # Below min_num
    with pytest.raises(ValueError):
        game.set_target_number(11) # Above max_num
    with pytest.raises(ValueError):
        game.set_target_number(-5) # Well below min_num
    with pytest.raises(ValueError):
        game.set_target_number(1000) # Well above max_num


# ============================================================================
# Tests for GameLogic class
# ============================================================================

def test_gamelogic_instantiation():
    """Test GameLogic can be instantiated"""
    instance = GameLogic()
    assert instance is not None


def test_gamelogic_reset_game(gamelogic_instance):
    """Test GameLogic.reset_game()"""
    # TODO: Add test implementation
    pass


def test_gamelogic_check_guess(gamelogic_instance):
    """Test GameLogic.check_guess()"""
    # TODO: Add test implementation
    pass


def test_gamelogic_get_attempts_made(gamelogic_instance):
    """Test GameLogic.get_attempts_made()"""
    # TODO: Add test implementation
    pass


def test_gamelogic_is_game_over(gamelogic_instance):
    """Test GameLogic.is_game_over()"""
    # TODO: Add test implementation
    pass


def test_gamelogic_get_range(gamelogic_instance):
    """Test GameLogic.get_range()"""
    # TODO: Add test implementation
    pass


def test_gamelogic_get_target_number(gamelogic_instance):
    """Test GameLogic.get_target_number()"""
    # TODO: Add test implementation
    pass


def test_gamelogic_set_target_number(gamelogic_instance):
    """Test GameLogic.set_target_number()"""
    # TODO: Add test implementation
    pass



# ============================================================================
# Edge Case Tests
# ============================================================================

