"""
Tests for src/cli.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from typing import Any, List, Dict

# Import module under test
from src.cli import *



# ============================================================================
# Fixtures
# ============================================================================


# ============================================================================
# Tests for main()
# ============================================================================

def test_main_addition_happy_path(mocker, capsys):
    """
    Tests basic addition operation with integer result via the CLI.
    Mocks user input and the underlying add function, verifying printed output.
    """
    mocker.patch('builtins.input', side_effect=["5 + 3", "quit"])

    # Mock the add and subtract functions as they appear in the module's namespace.
    # Replace '__main__' with the actual module name if `main` is imported
    # from a specific file (e.g., 'your_file_name.add').
    mock_add = mocker.patch('__main__.add', return_value=8)
    mock_subtract = mocker.patch('__main__.subtract')

    # Import main here to ensure mocks are in place for the module where main is defined.
    # If the provided source code is in 'cli_calculator.py', you'd typically
    # `from cli_calculator import main`. For this exercise, assuming it's in scope.
    from . import main
    main()

    captured = capsys.readouterr()
    assert "Welcome to the CLI Calculator!" in captured.out
    assert "Result: 8" in captured.out
    assert "Exiting calculator. Goodbye!" in captured.out
    mock_add.assert_called_once_with(5.0, 3.0)
    mock_subtract.assert_not_called()


def test_main_subtraction_float_result_happy_path(mocker, capsys):
    """
    Tests basic subtraction operation with float result via the CLI.
    Mocks user input and the underlying subtract function, verifying printed output.
    """
    mocker.patch('builtins.input', side_effect=["10.5 - 2.2", "quit"])
    mock_add = mocker.patch('__main__.add')
    mock_subtract = mocker.patch('__main__.subtract', return_value=8.3)

    from . import main
    main()

    captured = capsys.readouterr()
    assert "Result: 8.3" in captured.out
    mock_subtract.assert_called_once_with(10.5, 2.2)
    mock_add.assert_not_called()


def test_main_invalid_input_format_error(mocker, capsys):
    """
    Tests the CLI's handling of invalid input format.
    Verifies the exact error message from _parse_input is printed.
    """
    mocker.patch('builtins.input', side_effect=["5 +", "quit"])
    mocker.patch('__main__.add')
    mocker.patch('__main__.subtract')

    from . import main
    main()

    captured = capsys.readouterr()
    # CRITICAL: Copy error message exactly from source code
    assert "Invalid input format. Please use 'number operator number' (e.g., '5 + 3')." in captured.out
    assert "Result:" not in captured.out # No result should be printed after an error
    assert "Exiting calculator. Goodbye!" in captured.out


def test_main_invalid_numbers_error(mocker, capsys):
    """
    Tests the CLI's handling of non-numeric input for numbers.
    Verifies the exact error message from _parse_input is printed.
    """
    mocker.patch('builtins.input', side_effect=["a + 3", "quit"])
    mocker.patch('__main__.add')
    mocker.patch('__main__.subtract')

    from . import main
    main()

    captured = capsys.readouterr()
    # CRITICAL: Copy error message exactly from source code
    assert "Invalid numbers provided. Please ensure numbers are numeric (e.g., integers or floats)." in captured.out
    assert "Result:" not in captured.out
    assert "Exiting calculator. Goodbye!" in captured.out


def test_main_unsupported_operator_error(mocker, capsys):
    """
    Tests the CLI's handling of unsupported operators.
    Verifies the exact error message from main is printed.
    """
    mocker.patch('builtins.input', side_effect=["5 * 3", "quit"])
    mocker.patch('__main__.add')
    mocker.patch('__main__.subtract')

    from . import main
    main()

    captured = capsys.readouterr()
    # CRITICAL: Copy error message exactly from source code, including formatting
    assert "Unsupported operator: '*'. Only '+' and '-' are supported." in captured.out
    assert "Result:" not in captured.out
    assert "Exiting calculator. Goodbye!" in captured.out


# ============================================================================
# Edge Case Tests
# ============================================================================

