"""
Tests for src/game/guess_number.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.game.guess_number import *
import random # Required for mocking random.randint


# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def guessnumbergame_instance():
    """Fixture for GuessNumberGame instance"""
    return GuessNumberGame()



# ============================================================================
# Tests for __init__()
# ============================================================================


def test_init_defaults_correctly(mocker):
    """
    Tests that the GuessNumberGame initializes with default values when no arguments are provided.
    Verifies that internal attributes are set correctly based on defaults,
    and that `start_new_game()` has been called, setting initial game state.
    """
    mocker.patch('random.randint', return_value=50) # Mock secret number to be within default range
    game = GuessNumberGame()

    assert game._min_num == GuessNumberGame.DEFAULT_MIN_NUMBER
    assert game._max_num == GuessNumberGame.DEFAULT_MAX_NUMBER
    assert game._max_attempts == GuessNumberGame.DEFAULT_MAX_ATTEMPTS
    assert game._attempts_left == GuessNumberGame.DEFAULT_MAX_ATTEMPTS
    assert not game._game_won
    # Verify the secret number is within the default range after start_new_game()
    assert GuessNumberGame.DEFAULT_MIN_NUMBER <= game._secret_number <= GuessNumberGame.DEFAULT_MAX_NUMBER

def test_init_custom_parameters_valid(mocker):
    """
    Tests initialization with custom, valid min_num, max_num, and max_attempts.
    Verifies that internal attributes are set to the provided custom values,
    and that `start_new_game()` has been called with the correct range and attempts.
    """
    custom_min = 10
    custom_max = 50
    custom_attempts = 7
    mocker.patch('random.randint', return_value=30) # Mock secret number to be within custom range (10-50)
    game = GuessNumberGame(min_num=custom_min, max_num=custom_max, max_attempts=custom_attempts)

    assert game._min_num == custom_min
    assert game._max_num == custom_max
    assert game._max_attempts == custom_attempts
    assert game._attempts_left == custom_attempts
    assert not game._game_won
    # Verify the secret number is within the custom range after start_new_game()
    assert custom_min <= game._secret_number <= custom_max

def test_init_edge_case_min_range_and_attempts(mocker):
    """
    Tests initialization with edge-case valid parameters:
    - The smallest possible range (e.g., min_num=1, max_num=2).
    - The minimum positive number of attempts (max_attempts=1).
    """
    edge_min = 1
    edge_max = 2
    edge_attempts = 1
    mocker.patch('random.randint', return_value=1) # Mock secret number to be within edge-case range (1-2)
    game = GuessNumberGame(min_num=edge_min, max_num=edge_max, max_attempts=edge_attempts)

    assert game._min_num == edge_min
    assert game._max_num == edge_max
    assert game._max_attempts == edge_attempts
    assert game._attempts_left == edge_attempts
    assert not game._game_won
    # Verify the secret number is within the edge-case range
    assert edge_min <= game._secret_number <= edge_max

def test_init_raises_value_error_min_ge_max():
    """
    Tests that a ValueError is raised when min_num is greater than or equal to max_num.
    """
    with pytest.raises(ValueError):
        GuessNumberGame(min_num=10, max_num=10) # min_num == max_num
    with pytest.raises(ValueError):
        GuessNumberGame(min_num=20, max_num=10) # min_num > max_num

def test_init_raises_value_error_max_attempts_not_positive():
    """
    Tests that a ValueError is raised when max_attempts is not a positive integer (i.e., <= 0).
    """
    with pytest.raises(ValueError):
        GuessNumberGame(max_attempts=0)
    with pytest.raises(ValueError):
        GuessNumberGame(max_attempts=-5)

def test_init_raises_type_error_for_non_integer_parameters():
    """
    Tests that a TypeError is raised when min_num, max_num, or max_attempts
    are explicitly provided with non-integer values.
    """
    with pytest.raises(TypeError):
        GuessNumberGame(min_num=1.5)
    with pytest.raises(TypeError):
        GuessNumberGame(max_num="one hundred")
    with pytest.raises(TypeError):
        GuessNumberGame(max_attempts=[10])
    with pytest.raises(TypeError):
        # Correct usage for non-int type error for max_num, passing non-int string
        GuessNumberGame(min_num=1, max_num="one hundred", max_attempts=5)
    with pytest.raises(TypeError):
        GuessNumberGame(min_num=1.0, max_num=100, max_attempts=10)


# ============================================================================
# Tests for start_new_game()
# ============================================================================


@patch('random.randint')
def test_start_new_game_initial_state(mock_randint):
    """
    Tests that start_new_game correctly initializes the game state
    when a new GuessNumberGame instance is created.
    (The __init__ method calls start_new_game).
    """
    mock_randint.return_value = 50 # Mock the secret number to be 50

    game = GuessNumberGame()

    assert game._secret_number == 50
    assert game._attempts_left == GuessNumberGame.DEFAULT_MAX_ATTEMPTS
    assert game._game_won is False
    mock_randint.assert_called_once_with(
        GuessNumberGame.DEFAULT_MIN_NUMBER,
        GuessNumberGame.DEFAULT_MAX_NUMBER
    )


@patch('random.randint')
def test_start_new_game_resets_after_partial_play(mock_randint):
    """
    Tests that start_new_game resets the game state (new secret, full attempts, not won)
    after some attempts have been made and the game is still ongoing.
    """
    # Configure mock_randint to return different values on successive calls
    # First call for __init__, second for the explicit start_new_game call
    mock_randint.side_effect = [50, 25]

    game = GuessNumberGame() # __init__ calls start_new_game, secret is 50
    assert game.get_secret_number() == 50
    assert game.get_remaining_attempts() == game.get_max_attempts()

    # Make some guesses to change the game state
    game.check_guess(10) # Consumes an attempt
    game.check_guess(20) # Consumes another attempt

    assert game.get_remaining_attempts() == game.get_max_attempts() - 2
    assert game.is_game_over() is False
    assert game._game_won is False

    game.start_new_game() # Explicitly call start_new_game

    # Verify game state is reset
    assert game.get_secret_number() == 25 # New secret number
    assert game.get_remaining_attempts() == game.get_max_attempts() # Attempts reset
    assert game._game_won is False # Game won flag cleared
    assert game.is_game_over() is False
    assert mock_randint.call_count == 2


@patch('random.randint')
def test_start_new_game_resets_after_win(mock_randint):
    """
    Tests that start_new_game correctly resets the game state
    even after the player has won the previous game.
    """
    # Configure mock_randint for __init__ and subsequent start_new_game call
    mock_randint.side_effect = [50, 75]

    game = GuessNumberGame() # secret is 50
    assert game.get_secret_number() == 50

    # Win the game
    game.check_guess(50)
    assert game._game_won is True
    assert game.is_game_over() is True
    assert game.get_remaining_attempts() == game.get_max_attempts() - 1

    game.start_new_game() # Reset the game

    # Verify game state is reset
    assert game.get_secret_number() == 75 # New secret number
    assert game.get_remaining_attempts() == game.get_max_attempts() # Attempts reset
    assert game._game_won is False # Game won flag cleared
    assert game.is_game_over() is False
    assert mock_randint.call_count == 2


@patch('random.randint')
def test_start_new_game_resets_after_loss(mock_randint):
    """
    Tests that start_new_game correctly resets the game state
    even after the player has lost the previous game due to exhausting attempts.
    """
    # Configure mock_randint for __init__ and subsequent start_new_game call
    mock_randint.side_effect = [50, 10]

    game = GuessNumberGame(max_attempts=2) # secret is 50, few attempts
    assert game.get_secret_number() == 50
    assert game.get_max_attempts() == 2

    # Lose the game by exhausting attempts
    game.check_guess(1) # 1 attempt left
    game.check_guess(2) # 0 attempts left, game over
    assert game.get_remaining_attempts() == 0
    assert game._game_won is False
    assert game.is_game_over() is True

    game.start_new_game() # Reset the game

    # Verify game state is reset
    assert game.get_secret_number() == 10 # New secret number
    assert game.get_remaining_attempts() == 2 # Attempts reset to initial max
    assert game._game_won is False # Game won flag cleared
    assert game.is_game_over() is False
    assert mock_randint.call_count == 2


# ============================================================================
# Tests for check_guess()
# ============================================================================


def test_check_guess_type_error_non_int():
    """
    Test that check_guess raises TypeError if the guess is not an integer.
    """
    game = GuessNumberGame()
    with pytest.raises(TypeError):
        game.check_guess("not an int")
    with pytest.raises(TypeError):
        game.check_guess(10.5)
    with pytest.raises(TypeError):
        game.check_guess(None)

def test_check_guess_correct_first_try(mocker):
    """
    Test a correct guess on the first attempt.
    """
    # Mock random.randint to ensure a predictable secret number
    mocker.patch.object(random, 'randint', return_value=50)
    game = GuessNumberGame() # Secret number will be 50
    assert game.get_secret_number() == 50
    initial_attempts = game.get_remaining_attempts()

    result = game.check_guess(50)

    assert result == "Correct!"
    assert game.is_game_over() is True
    assert game._game_won is True
    assert game.get_remaining_attempts() == initial_attempts - 1

def test_check_guess_too_low(mocker):
    """
    Test a guess that is too low.
    """
    mocker.patch.object(random, 'randint', return_value=75)
    game = GuessNumberGame() # Secret number will be 75
    assert game.get_secret_number() == 75
    initial_attempts = game.get_remaining_attempts()

    result = game.check_guess(50)

    assert result == "Too low!"
    assert game.is_game_over() is False
    assert game._game_won is False
    assert game.get_remaining_attempts() == initial_attempts - 1

def test_check_guess_too_high(mocker):
    """
    Test a guess that is too high.
    """
    mocker.patch.object(random, 'randint', return_value=25)
    game = GuessNumberGame() # Secret number will be 25
    assert game.get_secret_number() == 25
    initial_attempts = game.get_remaining_attempts()

    result = game.check_guess(50)

    assert result == "Too high!"
    assert game.is_game_over() is False
    assert game._game_won is False
    assert game.get_remaining_attempts() == initial_attempts - 1

def test_check_guess_incorrect_on_last_attempt_loses_game(mocker):
    """
    Test an incorrect guess when only one attempt is left, leading to a loss.
    """
    mocker.patch.object(random, 'randint', return_value=10)
    # Configure the game with only 1 attempt
    game = GuessNumberGame(min_num=1, max_num=10, max_attempts=1)
    assert game.get_secret_number() == 10
    assert game.get_remaining_attempts() == 1

    # Make an incorrect guess
    result = game.check_guess(5)

    assert result == "Too low! Game over - you lost! The number was 10."
    assert game.is_game_over() is True
    assert game._game_won is False
    assert game.get_remaining_attempts() == 0

def test_check_guess_correct_on_last_attempt_wins_game(mocker):
    """
    Test a correct guess when only one attempt is left, leading to a win.
    """
    mocker.patch.object(random, 'randint', return_value=10)
    # Configure the game with only 1 attempt
    game = GuessNumberGame(min_num=1, max_num=10, max_attempts=1)
    assert game.get_secret_number() == 10
    assert game.get_remaining_attempts() == 1

    # Make a correct guess
    result = game.check_guess(10)

    assert result == "Correct!"
    assert game.is_game_over() is True
    assert game._game_won is True
    assert game.get_remaining_attempts() == 0

def test_check_guess_after_game_won_does_not_change_state(mocker):
    """
    Test that guessing after the game has been won returns the win message
    and does not consume attempts.
    """
    mocker.patch.object(random, 'randint', return_value=50)
    game = GuessNumberGame()
    game.check_guess(50) # Player wins

    assert game.is_game_over() is True
    assert game._game_won is True
    initial_remaining_attempts = game.get_remaining_attempts()

    # Try to guess again
    result = game.check_guess(51)

    assert result == "Game over - you won!"
    assert game.get_remaining_attempts() == initial_remaining_attempts # Attempts should not change
    assert game._game_won is True # Game won status remains true

def test_check_guess_after_game_lost_does_not_change_state(mocker):
    """
    Test that guessing after the game has been lost returns the loss message
    and does not consume attempts.
    """
    mocker.patch.object(random, 'randint', return_value=10)
    game = GuessNumberGame(max_attempts=1)
    game.check_guess(5) # Player makes an incorrect guess and loses

    assert game.is_game_over() is True
    assert game._game_won is False
    assert game.get_remaining_attempts() == 0 # Attempts are already 0

    # Try to guess again
    result = game.check_guess(8)

    assert result == f"Game over - you lost! The number was 10."
    assert game.get_remaining_attempts() == 0 # Attempts should not change
    assert game._game_won is False # Game won status remains false


# ============================================================================
# Tests for is_game_over()
# ============================================================================


def test_is_game_over_initial_state_not_over(mocker):
    """
    Test that the game is not over immediately after initialization.
    """
    mocker.patch('random.randint', return_value=5) # Mock for predictable secret
    game = GuessNumberGame(min_num=1, max_num=10, max_attempts=5)
    assert not game.is_game_over()
    assert game.get_remaining_attempts() == 5
    assert game.get_secret_number() == 5


def test_is_game_over_after_winning(mocker):
    """
    Test that the game is over when the player has won.
    """
    mocker.patch('random.randint', return_value=7) # Mock for predictable secret
    game = GuessNumberGame(min_num=1, max_num=10, max_attempts=5)
    
    # Check a correct guess
    game.check_guess(7)
    
    assert game.is_game_over()
    # It doesn't matter how many attempts are left if the game is won
    assert game.get_remaining_attempts() == 4 # 1 attempt used


def test_is_game_over_after_all_attempts_exhausted(mocker):
    """
    Test that the game is over when all attempts have been used, and player hasn't won.
    """
    mocker.patch('random.randint', return_value=2) # Mock for predictable secret
    game = GuessNumberGame(min_num=1, max_num=3, max_attempts=3)
    
    # Make incorrect guesses to exhaust attempts
    game.check_guess(1) # Attempts left: 2
    assert not game.is_game_over()
    game.check_guess(3) # Attempts left: 1
    assert not game.is_game_over()
    
    # Last attempt, still incorrect
    game.check_guess(1) # Attempts left: 0
    
    assert game.is_game_over()
    assert game.get_remaining_attempts() == 0


def test_is_game_over_just_before_losing(mocker):
    """
    Test that the game is not over when there is exactly one attempt left.
    """
    mocker.patch('random.randint', return_value=5) # Mock for predictable secret
    game = GuessNumberGame(min_num=1, max_num=10, max_attempts=2)

    # Use one attempt
    game.check_guess(1) # Attempts left: 1
    
    assert not game.is_game_over()
    assert game.get_remaining_attempts() == 1


def test_is_game_over_after_winning_on_last_attempt(mocker):
    """
    Test that the game is over if the player wins on their very last attempt.
    """
    mocker.patch('random.randint', return_value=5) # Mock for predictable secret
    game = GuessNumberGame(min_num=1, max_num=10, max_attempts=1)

    # Make the correct guess on the only attempt
    game.check_guess(5) # Attempts left: 0, game_won: True
    
    assert game.is_game_over()
    assert game.get_remaining_attempts() == 0


# ============================================================================
# Tests for get_remaining_attempts()
# ============================================================================


# Fixture to provide a GuessNumberGame instance with a predictable secret number
# This makes tests deterministic when dealing with check_guess.
@pytest.fixture
def game_with_fixed_secret(mocker):
    """
    Provides a GuessNumberGame instance where the secret number is fixed to 50
    and max_attempts is 5, using pytest-mock.
    """
    mocker.patch('random.randint', return_value=50)
    game = GuessNumberGame(min_num=1, max_num=100, max_attempts=5)
    return game

def test_get_remaining_attempts_initial_state_default():
    """
    Test that get_remaining_attempts returns the default maximum attempts
    immediately after a new game is initialized.
    """
    game = GuessNumberGame()
    expected_attempts = GuessNumberGame.DEFAULT_MAX_ATTEMPTS
    assert game.get_remaining_attempts() == expected_attempts

def test_get_remaining_attempts_initial_state_custom():
    """
    Test that get_remaining_attempts returns the custom maximum attempts
    immediately after a new game is initialized with custom settings.
    """
    custom_max_attempts = 7
    game = GuessNumberGame(max_attempts=custom_max_attempts)
    assert game.get_remaining_attempts() == custom_max_attempts

def test_get_remaining_attempts_after_incorrect_guesses(game_with_fixed_secret):
    """
    Test that get_remaining_attempts correctly decreases after several
    incorrect guesses.
    """
    game = game_with_fixed_secret # Secret is 50, max_attempts is 5
    initial_attempts = game.get_max_attempts()

    # Make first incorrect guess
    game.check_guess(20)
    assert game.get_remaining_attempts() == initial_attempts - 1

    # Make second incorrect guess
    game.check_guess(80)
    assert game.get_remaining_attempts() == initial_attempts - 2

def test_get_remaining_attempts_after_winning_game(game_with_fixed_secret):
    """
    Test that get_remaining_attempts reflects the attempts used
    up to the point of winning the game.
    """
    game = game_with_fixed_secret # Secret is 50, max_attempts is 5
    initial_attempts = game.get_max_attempts()

    game.check_guess(20) # 1st guess, 4 attempts left
    game.check_guess(80) # 2nd guess, 3 attempts left
    game.check_guess(50) # 3rd guess (correct), 2 attempts left

    assert game.get_remaining_attempts() == initial_attempts - 3
    assert game.is_game_over() # Verify game state is won

def test_get_remaining_attempts_after_losing_game_exhausted(mocker):
    """
    Test that get_remaining_attempts is 0 when all attempts are exhausted
    and the player loses the game.
    """
    mocker.patch('random.randint', return_value=10) # Fix secret to 10
    game = GuessNumberGame(min_num=1, max_num=20, max_attempts=3)

    game.check_guess(1) # 1st guess, 2 attempts left
    game.check_guess(2) # 2nd guess, 1 attempt left
    game.check_guess(3) # 3rd guess (last attempt), 0 attempts left

    assert game.get_remaining_attempts() == 0
    assert game.is_game_over() # Verify game state is lost

def test_get_remaining_attempts_after_start_new_game(game_with_fixed_secret):
    """
    Test that calling start_new_game resets the remaining attempts
    to the maximum allowed attempts.
    """
    game = game_with_fixed_secret # Secret is 50, max_attempts is 5
    initial_max_attempts = game.get_max_attempts()

    # Consume some attempts
    game.check_guess(20)
    assert game.get_remaining_attempts() == initial_max_attempts - 1

    # Start a new game
    game.start_new_game()

    # Attempts should be reset to initial_max_attempts
    assert game.get_remaining_attempts() == initial_max_attempts
    assert not game.is_game_over() # Verify game is no longer over


# ============================================================================
# Tests for get_secret_number()
# ============================================================================


def test_get_secret_number_default_range_happy_path(mocker):
    """
    Tests that get_secret_number returns the expected secret number
    when initialized with default range settings.
    Mocks random.randint to ensure a predictable secret number.
    """
    # Mock random.randint to always return a specific value (e.g., 50)
    # This ensures determinism for the secret number generation.
    mocker.patch('random.randint', return_value=50)

    game = GuessNumberGame()
    secret = game.get_secret_number()

    assert secret == 50
    assert GuessNumberGame.DEFAULT_MIN_NUMBER <= secret <= GuessNumberGame.DEFAULT_MAX_NUMBER

def test_get_secret_number_custom_range_min_edge_case(mocker):
    """
    Tests get_secret_number with a custom range, verifying it returns the
    minimum value of the range when random.randint is mocked to return it.
    """
    min_val, max_val = 10, 20
    # Mock random.randint to return the lower bound of the custom range
    mocker.patch('random.randint', return_value=min_val)

    game = GuessNumberGame(min_num=min_val, max_num=max_val)
    secret = game.get_secret_number()

    assert secret == min_val
    assert min_val <= secret <= max_val

def test_get_secret_number_custom_range_max_edge_case(mocker):
    """
    Tests get_secret_number with a custom range, verifying it returns the
    maximum value of the range when random.randint is mocked to return it.
    """
    min_val, max_val = 10, 20
    # Mock random.randint to return the upper bound of the custom range
    mocker.patch('random.randint', return_value=max_val)

    game = GuessNumberGame(min_num=min_val, max_num=max_val)
    secret = game.get_secret_number()

    assert secret == max_val
    assert min_val <= secret <= max_val

def test_get_secret_number_consistent_during_gameplay(mocker):
    """
    Verifies that the secret number remains constant throughout the duration
    of a single game, even after multiple guesses.
    """
    mocker.patch('random.randint', return_value=77) # Set a fixed secret number

    game = GuessNumberGame()
    initial_secret = game.get_secret_number()
    assert initial_secret == 77

    # Make several guesses
    game.check_guess(50) # Too low
    assert game.get_secret_number() == initial_secret

    game.check_guess(90) # Too high
    assert game.get_secret_number() == initial_secret

    game.check_guess(77) # Correct guess, game ends
    assert game.get_secret_number() == initial_secret

def test_get_secret_number_changes_on_new_game(mocker):
    """
    Ensures that calling start_new_game generates a new secret number,
    and get_secret_number reflects this change.
    """
    # Use side_effect to make random.randint return different values
    # on successive calls (first for __init__, second for start_new_game)
    mocker.patch('random.randint', side_effect=[42, 88])

    game = GuessNumberGame()
    first_secret = game.get_secret_number()
    assert first_secret == 42 # Secret from the initial __init__ call

    game.start_new_game()
    second_secret = game.get_secret_number()
    assert second_secret == 88 # Secret from the start_new_game call

    assert first_secret != second_secret


# ============================================================================
# Tests for get_range()
# ============================================================================

import pytest
from src.game.guess_number import GuessNumberGame

def test_get_range_default_values():
    """
    Test get_range with a game initialized with default min/max numbers.
    """
    game = GuessNumberGame()
    expected_range = (GuessNumberGame.DEFAULT_MIN_NUMBER, GuessNumberGame.DEFAULT_MAX_NUMBER)
    assert game.get_range() == expected_range

def test_get_range_custom_values():
    """
    Test get_range with a game initialized with custom min/max numbers.
    """
    min_val = 50
    max_val = 150
    game = GuessNumberGame(min_num=min_val, max_num=max_val)
    expected_range = (min_val, max_val)
    assert game.get_range() == expected_range

def test_get_range_edge_case_small_range():
    """
    Test get_range with a game initialized with a very small valid range.
    """
    min_val = 1
    max_val = 2
    game = GuessNumberGame(min_num=min_val, max_num=max_val)
    expected_range = (min_val, max_val)
    assert game.get_range() == expected_range

def test_get_range_edge_case_large_numbers():
    """
    Test get_range with a game initialized with larger numbers for min/max.
    """
    min_val = 1000
    max_val = 50000
    game = GuessNumberGame(min_num=min_val, max_num=max_val)
    expected_range = (min_val, max_val)
    assert game.get_range() == expected_range


# ============================================================================
# Tests for get_max_attempts()
# ============================================================================

import pytest
from src.game.guess_number import GuessNumberGame

def test_get_max_attempts_default_value():
    """
    Test that get_max_attempts returns the default value when not specified.
    """
    game = GuessNumberGame()
    assert game.get_max_attempts() == GuessNumberGame.DEFAULT_MAX_ATTEMPTS

def test_get_max_attempts_custom_value():
    """
    Test that get_max_attempts returns the custom value provided during initialization.
    """
    custom_attempts = 7
    game = GuessNumberGame(max_attempts=custom_attempts)
    assert game.get_max_attempts() == custom_attempts

def test_get_max_attempts_after_game_progress():
    """
    Test that get_max_attempts always returns the initial maximum attempts,
    even after attempts have been consumed.
    """
    initial_max_attempts = 5
    game = GuessNumberGame(max_attempts=initial_max_attempts)

    # Consume some attempts
    secret_num = game.get_secret_number()
    game.check_guess(secret_num + 1) # Guesses high
    game.check_guess(secret_num - 1) # Guesses low

    # The maximum attempts should remain the same
    assert game.get_max_attempts() == initial_max_attempts
    # Verify remaining attempts are different to ensure game progressed
    assert game.get_remaining_attempts() < initial_max_attempts

def test_get_max_attempts_edge_case_one_attempt():
    """
    Test get_max_attempts when initialized with only one attempt allowed.
    """
    game = GuessNumberGame(max_attempts=1)
    assert game.get_max_attempts() == 1


# ============================================================================
# Tests for GuessNumberGame class
# ============================================================================

def test_guessnumbergame_instantiation():
    """Test GuessNumberGame can be instantiated"""
    instance = GuessNumberGame()
    assert instance is not None


def test_guessnumbergame_start_new_game(guessnumbergame_instance):
    """Test GuessNumberGame.start_new_game()"""
    # TODO: Add test implementation
    pass


def test_guessnumbergame_check_guess(guessnumbergame_instance):
    """Test GuessNumberGame.check_guess()"""
    # TODO: Add test implementation
    pass


def test_guessnumbergame_is_game_over(guessnumbergame_instance):
    """Test GuessNumberGame.is_game_over()"""
    # TODO: Add test implementation
    pass


def test_guessnumbergame_get_remaining_attempts(guessnumbergame_instance):
    """Test GuessNumberGame.get_remaining_attempts()"""
    # TODO: Add test implementation
    pass


def test_guessnumbergame_get_secret_number(guessnumbergame_instance):
    """Test GuessNumberGame.get_secret_number()"""
    # TODO: Add test implementation
    pass


def test_guessnumbergame_get_range(guessnumbergame_instance):
    """Test GuessNumberGame.get_range()"""
    # TODO: Add test implementation
    pass


def test_guessnumbergame_get_max_attempts(guessnumbergame_instance):
    """Test GuessNumberGame.get_max_attempts()"""
    # TODO: Add test implementation
    pass



# ============================================================================
# Edge Case Tests
# ============================================================================