"""
Tests for src/game/cli_ui.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.game.cli_ui import *



# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def cliui_instance():
    """Fixture for CliUI instance"""
    return CliUI()


@pytest.fixture
def mock_db():
    """Fixture for mock database"""
    db = Mock()
    db.query.return_value = []
    return db



# ============================================================================
# Tests for display_welcome_message()
# ============================================================================

import pytest
from src.game.cli_ui import CliUI

def test_display_welcome_message_standard_case(capsys):
    """
    Test display_welcome_message with standard, valid game parameters.
    Ensures the welcome message and rules are printed correctly.
    """
    min_num = 1
    max_num = 100
    max_attempts = 5

    CliUI.display_welcome_message(min_num, max_num, max_attempts)
    captured = capsys.readouterr()

    expected_output = (
        "--------------------------------------------------\n"
        "         GUESS THE NUMBER GAME         \n"
        "--------------------------------------------------\n"
        "I'm thinking of a number between 1 and 100.\n"
        "You have 5 attempts to guess it.\n"
        "Good luck!\n\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_welcome_message_single_attempt_and_range(capsys):
    """
    Test display_welcome_message with edge-case parameters:
    - Minimum and maximum numbers are the same (range of 1).
    - Only one attempt allowed.
    """
    min_num = 42
    max_num = 42
    max_attempts = 1

    CliUI.display_welcome_message(min_num, max_num, max_attempts)
    captured = capsys.readouterr()

    expected_output = (
        "--------------------------------------------------\n"
        "         GUESS THE NUMBER GAME         \n"
        "--------------------------------------------------\n"
        "I'm thinking of a number between 42 and 42.\n"
        "You have 1 attempts to guess it.\n"
        "Good luck!\n\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_welcome_message_large_numbers(capsys):
    """
    Test display_welcome_message with larger numerical inputs
    to ensure formatting handles multi-digit numbers correctly.
    """
    min_num = 1000
    max_num = 9999
    max_attempts = 100

    CliUI.display_welcome_message(min_num, max_num, max_attempts)
    captured = capsys.readouterr()

    expected_output = (
        "--------------------------------------------------\n"
        "         GUESS THE NUMBER GAME         \n"
        "--------------------------------------------------\n"
        "I'm thinking of a number between 1000 and 9999.\n"
        "You have 100 attempts to guess it.\n"
        "Good luck!\n\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""


# ============================================================================
# Tests for prompt_for_guess()
# ============================================================================

The `prompt_for_guess` function directly calls `input()`, which would block headless CI environments and cause `StopIteration` errors. According to the provided rules (Rule 9: "CRITICAL: DO NOT write tests for functions that call `input()`. ... If the function requires `input()`, do not generate a test for it."), I cannot generate test cases for this function.


# ============================================================================
# Tests for display_feedback()
# ============================================================================

import pytest
from src.game.cli_ui import CliUI

def test_display_feedback_simple_message(capsys):
    """
    Test that display_feedback correctly prints a simple message to standard output.
    """
    message = "Your guess was too high. Try again!"
    CliUI.display_feedback(message)
    captured = capsys.readouterr()
    assert captured.out == message + "\n"
    assert captured.err == ""

def test_display_feedback_empty_message(capsys):
    """
    Test that display_feedback handles an empty string message correctly.
    It should print an empty line (just a newline character).
    """
    message = ""
    CliUI.display_feedback(message)
    captured = capsys.readouterr()
    assert captured.out == message + "\n" # print() adds a newline even for empty string
    assert captured.err == ""

def test_display_feedback_message_with_special_characters_and_numbers(capsys):
    """
    Test that display_feedback correctly prints a message containing numbers and special characters.
    """
    message = "Level 5 unlocked! Score: 12345. 🎉"
    CliUI.display_feedback(message)
    captured = capsys.readouterr()
    assert captured.out == message + "\n"
    assert captured.err == ""

def test_display_feedback_multiline_message_string(capsys):
    """
    Test that display_feedback correctly prints a string containing embedded newlines.
    The `print` function will add one additional newline at the end.
    """
    message = "Line 1 of feedback.\nLine 2 of feedback."
    CliUI.display_feedback(message)
    captured = capsys.readouterr()
    # The `print` function itself adds a newline after the entire string,
    # so the output includes the original embedded newlines plus one at the very end.
    assert captured.out == message + "\n"
    assert captured.err == ""


# ============================================================================
# Tests for display_win_message()
# ============================================================================

import pytest
from src.game.cli_ui import CliUI # Import the class as the method is static

def test_display_win_message_happy_path(capsys):
    """
    Tests display_win_message with a typical secret number and attempts.
    """
    secret_number = 42
    attempts_taken = 3
    CliUI.display_win_message(secret_number, attempts_taken)
    captured = capsys.readouterr()

    expected_output = (
        f"\n🎉 Congratulations! You guessed the number {secret_number} correctly!\n"
        f"It took you {attempts_taken} attempts.\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_win_message_min_attempts(capsys):
    """
    Tests display_win_message when the player wins in 1 attempt.
    """
    secret_number = 10
    attempts_taken = 1
    CliUI.display_win_message(secret_number, attempts_taken)
    captured = capsys.readouterr()

    expected_output = (
        f"\n🎉 Congratulations! You guessed the number {secret_number} correctly!\n"
        f"It took you {attempts_taken} attempts.\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_win_message_many_attempts(capsys):
    """
    Tests display_win_message with a higher number of attempts taken.
    """
    secret_number = 99
    attempts_taken = 15
    CliUI.display_win_message(secret_number, attempts_taken)
    captured = capsys.readouterr()

    expected_output = (
        f"\n🎉 Congratulations! You guessed the number {secret_number} correctly!\n"
        f"It took you {attempts_taken} attempts.\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_win_message_zero_values(capsys):
    """
    Tests display_win_message with zero for secret_number and attempts_taken.
    While unlikely in a real game, the function should handle displaying them.
    """
    secret_number = 0
    attempts_taken = 0
    CliUI.display_win_message(secret_number, attempts_taken)
    captured = capsys.readouterr()

    expected_output = (
        f"\n🎉 Congratulations! You guessed the number {secret_number} correctly!\n"
        f"It took you {attempts_taken} attempts.\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_win_message_negative_values(capsys):
    """
    Tests display_win_message with negative values for secret_number and attempts_taken.
    The function should simply display them as provided.
    """
    secret_number = -5
    attempts_taken = -2
    CliUI.display_win_message(secret_number, attempts_taken)
    captured = capsys.readouterr()

    expected_output = (
        f"\n🎉 Congratulations! You guessed the number {secret_number} correctly!\n"
        f"It took you {attempts_taken} attempts.\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""


# ============================================================================
# Tests for display_lose_message()
# ============================================================================

import pytest
from src.game.cli_ui import CliUI # The function is a static method of CliUI

def test_display_lose_message_positive_number(capsys):
    """
    Test CliUI.display_lose_message with a typical positive secret number.
    Verifies the correct game over message is printed to stdout.
    """
    secret_number = 42
    CliUI.display_lose_message(secret_number)
    captured = capsys.readouterr()
    expected_output = (
        f"\nGame Over! You ran out of attempts.\n"
        f"The secret number was {secret_number}.\n"
        f"Better luck next time!\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_lose_message_zero_number(capsys):
    """
    Test CliUI.display_lose_message with zero as the secret number.
    Verifies the correct game over message is printed when the secret is 0.
    """
    secret_number = 0
    CliUI.display_lose_message(secret_number)
    captured = capsys.readouterr()
    expected_output = (
        f"\nGame Over! You ran out of attempts.\n"
        f"The secret number was {secret_number}.\n"
        f"Better luck next time!\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""

def test_display_lose_message_negative_number(capsys):
    """
    Test CliUI.display_lose_message with a negative secret number.
    Verifies the correct game over message is printed when the secret is a negative number.
    """
    secret_number = -15
    CliUI.display_lose_message(secret_number)
    captured = capsys.readouterr()
    expected_output = (
        f"\nGame Over! You ran out of attempts.\n"
        f"The secret number was {secret_number}.\n"
        f"Better luck next time!\n"
        f"{'-' * 50}\n"
    )
    assert captured.out == expected_output
    assert captured.err == ""


# ============================================================================
# Tests for prompt_to_play_again()
# ============================================================================

**CRITICAL NOTE: Rule 9 states:** "CRITICAL: DO NOT write tests for functions that call `input()`. They block headless CI and cause StopIteration errors. Only test pure logic/math functions. If the function requires `input()`, do not generate a test for it."

The `prompt_to_play_again` function directly calls `input()` to receive user input. Therefore, according to the provided rules, I cannot generate test cases for this function. Testing functions that interact with `input()` requires mocking `input()`, which is explicitly disallowed by Rule 9's intent to avoid such blocking behavior in headless CI.


# ============================================================================
# Tests for display_error_message()
# ============================================================================

import sys
import pytest
from src.game.cli_ui import CliUI # Assuming CliUI is the class, and display_error_message is a static method

def test_display_error_message_standard(capsys):
    """
    Test that a standard error message is displayed correctly to stderr.
    """
    test_message = "Invalid input. Please try again."
    CliUI.display_error_message(test_message)
    captured = capsys.readouterr()
    assert captured.out == ""  # No output to stdout
    assert captured.err == f"ERROR: {test_message}\n"

def test_display_error_message_empty_string(capsys):
    """
    Test that an empty string message is displayed correctly to stderr.
    """
    test_message = ""
    CliUI.display_error_message(test_message)
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == f"ERROR: {test_message}\n"

def test_display_error_message_with_special_characters(capsys):
    """
    Test that an error message with special characters is displayed correctly to stderr.
    """
    test_message = "File not found! Path: /usr/local/data?"
    CliUI.display_error_message(test_message)
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == f"ERROR: {test_message}\n"

def test_display_error_message_multiple_calls(capsys):
    """
    Test that multiple consecutive error messages are displayed correctly to stderr.
    """
    msg1 = "First error!"
    msg2 = "Second error occurred."
    CliUI.display_error_message(msg1)
    CliUI.display_error_message(msg2)
    captured = capsys.readouterr()
    assert captured.out == ""
    assert captured.err == f"ERROR: {msg1}\nERROR: {msg2}\n"


# ============================================================================
# Tests for CliUI class
# ============================================================================

def test_cliui_instantiation():
    """Test CliUI can be instantiated"""
    instance = CliUI()
    assert instance is not None


def test_cliui_display_welcome_message(cliui_instance):
    """Test CliUI.display_welcome_message()"""
    # TODO: Add test implementation
    pass


def test_cliui_prompt_for_guess(cliui_instance):
    """Test CliUI.prompt_for_guess()"""
    # TODO: Add test implementation
    pass


def test_cliui_display_feedback(cliui_instance):
    """Test CliUI.display_feedback()"""
    # TODO: Add test implementation
    pass


def test_cliui_display_win_message(cliui_instance):
    """Test CliUI.display_win_message()"""
    # TODO: Add test implementation
    pass


def test_cliui_display_lose_message(cliui_instance):
    """Test CliUI.display_lose_message()"""
    # TODO: Add test implementation
    pass


def test_cliui_prompt_to_play_again(cliui_instance):
    """Test CliUI.prompt_to_play_again()"""
    # TODO: Add test implementation
    pass


def test_cliui_display_error_message(cliui_instance):
    """Test CliUI.display_error_message()"""
    # TODO: Add test implementation
    pass



# ============================================================================
# Edge Case Tests
# ============================================================================

