"""
Tests for src/temperature/conversions.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.temperature.conversions import *



# ============================================================================
# Fixtures
# ============================================================================


# ============================================================================
# Tests for celsius_to_fahrenheit()
# ============================================================================

import pytest
from src.temperature.conversions import celsius_to_fahrenheit

def test_celsius_to_fahrenheit_standard_values():
    """
    Tests the conversion for common temperature values including freezing,
    boiling, positive, and negative temperatures.
    """
    # Freezing point
    assert celsius_to_fahrenheit(0) == pytest.approx(32.0, rel=1e-3)
    # Boiling point
    assert celsius_to_fahrenheit(100) == pytest.approx(212.0, rel=1e-3)
    # Room temperature
    assert celsius_to_fahrenheit(25) == pytest.approx(77.0, rel=1e-3)
    # Negative temperature
    assert celsius_to_fahrenheit(-10) == pytest.approx(14.0, rel=1e-3)

def test_celsius_to_fahrenheit_absolute_zero():
    """
    Tests the conversion for absolute zero, an important physical constant.
    """
    # Absolute zero in Celsius
    assert celsius_to_fahrenheit(-273.15) == pytest.approx(-459.67, rel=1e-3)

def test_celsius_to_fahrenheit_extreme_values():
    """
    Tests the conversion for very large positive, large negative,
    and very small decimal values.
    """
    # Large positive value
    assert celsius_to_fahrenheit(1000) == pytest.approx(1832.0, rel=1e-3)
    # Large negative value
    assert celsius_to_fahrenheit(-500) == pytest.approx(-868.0, rel=1e-3)
    # Small decimal value
    assert celsius_to_fahrenheit(0.001) == pytest.approx(32.0018, rel=1e-3)

def test_celsius_to_fahrenheit_type_error_for_invalid_input():
    """
    Tests that a TypeError is raised when non-numeric input types are provided.
    """
    with pytest.raises(TypeError):
        celsius_to_fahrenheit("25")
    with pytest.raises(TypeError):
        celsius_to_fahrenheit(None)
    with pytest.raises(TypeError):
        celsius_to_fahrenheit([10])
    with pytest.raises(TypeError):
        celsius_to_fahrenheit(True)


# ============================================================================
# Edge Case Tests
# ============================================================================

