"""
Tests for src/expression_parser.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.expression_parser import *



# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def expressionparser_instance():
    """Fixture for ExpressionParser instance"""
    return ExpressionParser()



# ============================================================================
# Tests for __init__()
# ============================================================================

import pytest
import math
from src.expression_parser import ExpressionParser

def test_expression_parser_initialization_successful():
    """
    Test that the ExpressionParser initializes successfully without errors.
    """
    parser = ExpressionParser()
    assert isinstance(parser, ExpressionParser)

def test_allowed_functions_and_constants_are_class_attributes():
    """
    Test that _allowed_functions and _allowed_constants are correctly defined
    as class-level attributes and are accessible via the instance.
    """
    parser = ExpressionParser()
    
    # Check if attributes exist
    assert hasattr(parser, '_allowed_functions')
    assert hasattr(parser, '_allowed_constants')
    
    # Check if they are of the correct type (dictionaries)
    assert isinstance(parser._allowed_functions, dict)
    assert isinstance(parser._allowed_constants, dict)

def test_allowed_functions_and_constants_content_integrity():
    """
    Test that the _allowed_functions and _allowed_constants dictionaries
    contain expected key-value pairs, verifying their initial content.
    """
    parser = ExpressionParser()

    # Check some specific functions
    assert 'sin' in parser._allowed_functions
    assert parser._allowed_functions['sin'] is math.sin
    assert 'abs' in parser._allowed_functions # Test a built-in function
    assert parser._allowed_functions['abs'] is abs
    assert 'log' in parser._allowed_functions
    assert parser._allowed_functions['log'] is math.log
    
    # Check some specific constants
    assert 'pi' in parser._allowed_constants
    assert parser._allowed_constants['pi'] is math.pi
    assert 'e' in parser._allowed_constants
    assert parser._allowed_constants['e'] is math.e
    assert 'inf' in parser._allowed_constants
    assert parser._allowed_constants['inf'] is math.inf

def test_allowed_functions_and_constants_are_not_empty():
    """
    Test that the allowed function and constant dictionaries are not empty,
    indicating they were populated as expected.
    """
    parser = ExpressionParser()
    assert len(parser._allowed_functions) > 0
    assert len(parser._allowed_constants) > 0


# ============================================================================
# Tests for parse()
# ============================================================================

import pytest
import math
from src.expression_parser import ExpressionParser

# Instantiate the parser once for all tests
# Note: The prompt's suggested import `from src.expression_parser import parse` implies
# `parse` is a standalone function. However, based on the provided source code,
# `parse` is an instance method of the `ExpressionParser` class.
# Therefore, we import `ExpressionParser` and instantiate it to call `parse`.
parser = ExpressionParser()

def test_parse_happy_path_basic_arithmetic_and_implicit_multiplication():
    """
    Test basic arithmetic operations, variable 'x', and various forms of implicit multiplication.
    """
    # Simple addition with 'x'
    func = parser.parse('x + 1')
    assert func(5) == 6
    assert func(-1) == 0

    # Implicit multiplication: number followed by 'x'
    func = parser.parse('2x')
    assert func(3) == 6
    assert func(0.5) == 1
    assert func(-4) == -8

    # Implicit multiplication: number followed by constant (pi)
    func = parser.parse('2.5pi')
    assert func(0) == pytest.approx(2.5 * math.pi)
    assert func(100) == pytest.approx(2.5 * math.pi) # 'x' is unused

    # Implicit multiplication: parentheses followed by parentheses
    func = parser.parse('(x+1)(x-1)')
    assert func(5) == (5 + 1) * (5 - 1)
    assert func(1) == (1 + 1) * (1 - 1)
    assert func(0) == (0 + 1) * (0 - 1)

    # Implicit multiplication: number followed by parentheses
    func = parser.parse('2(x+3)')
    assert func(2) == 2 * (2 + 3)
    assert func(-3) == 2 * (-3 + 3)

    # Exponentiation and mixed operations with whitespace
    func = parser.parse('  x^2 + 2x - 3  ')
    assert func(4) == 4**2 + 2*4 - 3
    assert func(-1) == (-1)**2 + 2*(-1) - 3

def test_parse_happy_path_functions_and_constants():
    """
    Test handling of allowed mathematical functions and constants from the `math` module.
    """
    # Trigonometric function and constant
    func = parser.parse('sin(pi/2)')
    assert func(0) == pytest.approx(math.sin(math.pi/2))
    assert func(10) == pytest.approx(math.sin(math.pi/2)) # 'x' is unused

    # Multiple functions (sqrt, log10)
    func = parser.parse('sqrt(4) + log10(100)')
    assert func(0) == pytest.approx(math.sqrt(4) + math.log10(100))

    # Constant 'e' and exponentiation
    func = parser.parse('e^x')
    assert func(2) == pytest.approx(math.e**2)
    assert func(1) == pytest.approx(math.e**1)

    # Built-in functions (abs, floor)
    func = parser.parse('abs(-5) + floor(3.7)')
    assert func(0) == pytest.approx(abs(-5) + math.floor(3.7))

    # Function with 'x' and another function (degrees)
    func = parser.parse('x * degrees(pi)')
    assert func(0.5) == pytest.approx(0.5 * math.degrees(math.pi))
    assert func(1) == pytest.approx(1 * math.degrees(math.pi))

    # Complex expression with nested functions and 'x'
    func = parser.parse('ceil(sin(x) + cos(x)) + round(tan(x))')
    x_val = math.pi / 4 # A known value where sin, cos, tan are simple
    expected = math.ceil(math.sin(x_val) + math.cos(x_val)) + round(math.tan(x_val))
    assert func(x_val) == pytest.approx(expected)

def test_parse_error_invalid_input_types():
    """
    Test that parse raises TypeError when the input expression is not a string.
    """
    with pytest.raises(TypeError):
        parser.parse(None)
    with pytest.raises(TypeError):
        parser.parse(123)
    with pytest.raises(TypeError):
        parser.parse([])
    with pytest.raises(TypeError):
        parser.parse({'expr': 'x+1'})

def test_parse_error_invalid_expressions():
    """
    Test that parse raises ValueError for various invalid expression patterns,
    including empty strings, invalid characters, unbalanced parentheses,
    unknown identifiers, and general syntax errors.
    """
    # Empty or whitespace-only expressions
    with pytest.raises(ValueError):
        parser.parse('')
    with pytest.raises(ValueError):
        parser.parse('   ')

    # Expressions with invalid or disallowed characters
    with pytest.raises(ValueError):
        parser.parse('1 + $')
    with pytest.raises(ValueError):
        parser.parse('x @ 2')
    with pytest.raises(ValueError):
        parser.parse('1 & 2')

    # Expressions with unbalanced parentheses
    with pytest.raises(ValueError):
        parser.parse('1 + (2') # Missing ')'
    with pytest.raises(ValueError):
        parser.parse('1 + 2)') # Missing '('
    with pytest.raises(ValueError):
        parser.parse('((x+1)')
    with pytest.raises(ValueError):
        parser.parse('(x+1))')

    # Expressions with unknown identifiers (functions or constants not in _allowed_lists)
    with pytest.raises(ValueError):
        parser.parse('unknown_func(x)')
    with pytest.raises(ValueError):
        parser.parse('x + abc')
    with pytest.raises(ValueError):
        parser.parse('2 * MyVar')

    # General syntax errors or issues caught during dummy evaluation
    with pytest.raises(ValueError):
        parser.parse('1 + * 2') # Operator misuse
    with pytest.raises(ValueError):
        # `math.sin()` expects 1 argument. Calling `sin()` without arguments
        # results in a TypeError during dummy eval, which is caught and re-raised as ValueError.
        parser.parse('sin()')
    with pytest.raises(ValueError):
        parser.parse('x / ') # Incomplete expression
    with pytest.raises(ValueError):
        parser.parse('+ x') # Leading operator
    with pytest.raises(ValueError):
        parser.parse('x -') # Trailing operator
    with pytest.raises(ValueError):
        parser.parse('x**') # Incomplete exponentiation


# ============================================================================
# Tests for ExpressionParser class
# ============================================================================

def test_expressionparser_instantiation():
    """Test ExpressionParser can be instantiated"""
    instance = ExpressionParser()
    assert instance is not None


def test_expressionparser_parse(expressionparser_instance):
    """Test ExpressionParser.parse()"""
    # TODO: Add test implementation
    pass



# ============================================================================
# Edge Case Tests
# ============================================================================

def test_parse_empty_string():
    """Test parse handles empty string"""
    # TODO: Add test for empty string input
    pass


