"""
Tests for src/graph_evaluator.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.graph_evaluator import *



# ============================================================================
# Fixtures
# ============================================================================

@pytest.fixture
def graphevaluator_instance():
    """Fixture for GraphEvaluator instance"""
    return GraphEvaluator()



# ============================================================================
# Tests for evaluate_expression_for_range()
# ============================================================================

import pytest
import math
from src.graph_evaluator import GraphEvaluator

def test_simple_linear_function_happy_path():
    """
    Test evaluation of a simple linear function (y = 2x + 1) over a positive range.
    Verifies correct point generation and evaluation for a basic case.
    """
    def linear_func(x):
        return 2 * x + 1

    x_start = 0.0
    x_end = 2.0
    num_points = 3 # x-values: 0, 1, 2

    # Expected y-values: 2*0+1=1, 2*1+3, 2*2+1=5
    expected_coordinates = [(0.0, 1.0), (1.0, 3.0), (2.0, 5.0)]

    result = GraphEvaluator.evaluate_expression_for_range(linear_func, x_start, x_end, num_points)

    assert len(result) == len(expected_coordinates)
    for i in range(len(result)):
        assert result[i][0] == pytest.approx(expected_coordinates[i][0], rel=1e-3)
        assert result[i][1] == pytest.approx(expected_coordinates[i][1], rel=1e-3)

def test_function_with_domain_error_sqrt_negative_produces_nan():
    """
    Test a function that produces domain errors (e.g., sqrt of a negative number).
    The corresponding y-values should be float('nan').
    """
    def sqrt_func(x):
        return math.sqrt(x - 1)

    x_start = 0.0
    x_end = 2.0
    num_points = 3 # x-values: 0, 1, 2

    # Expected: sqrt(0-1)=NaN, sqrt(1-1)=0, sqrt(2-1)=1
    result = GraphEvaluator.evaluate_expression_for_range(sqrt_func, x_start, x_end, num_points)

    assert len(result) == num_points
    assert result[0][0] == pytest.approx(0.0, rel=1e-3)
    assert math.isnan(result[0][1]) # x=0, sqrt(-1) -> NaN

    assert result[1][0] == pytest.approx(1.0, rel=1e-3)
    assert result[1][1] == pytest.approx(0.0, rel=1e-3) # x=1, sqrt(0) -> 0

    assert result[2][0] == pytest.approx(2.0, rel=1e-3)
    assert result[2][1] == pytest.approx(1.0, rel=1e-3) # x=2, sqrt(1) -> 1

def test_division_by_zero_and_other_runtime_errors_produce_nan():
    """
    Test a function that produces various runtime errors (ZeroDivisionError, generic Exception).
    The corresponding y-values should be float('nan').
    """
    def func_with_errors(x):
        if x == 0:
            return 1 / x  # This will raise ZeroDivisionError
        elif x == 0.5:
            raise RuntimeError("Custom error for testing purposes") # Generic Exception
        return 1 / x

    x_start = -1.0
    x_end = 1.0
    num_points = 5 # x-values: -1, -0.5, 0, 0.5, 1

    result = GraphEvaluator.evaluate_expression_for_range(func_with_errors, x_start, x_end, num_points)

    assert len(result) == num_points
    assert result[0] == pytest.approx((-1.0, -1.0), rel=1e-3)
    assert result[1] == pytest.approx((-0.5, -2.0), rel=1e-3)
    
    assert result[2][0] == pytest.approx(0.0, rel=1e-3)
    assert math.isnan(result[2][1]) # x=0, ZeroDivisionError -> NaN
    
    assert result[3][0] == pytest.approx(0.5, rel=1e-3)
    assert math.isnan(result[3][1]) # x=0.5, RuntimeError -> NaN
    
    assert result[4] == pytest.approx((1.0, 1.0), rel=1e-3)

def test_edge_case_num_points_two_and_negative_range():
    """
    Test the minimum valid number of points (2) and a range including negative values.
    """
    def quadratic_func(x):
        return x * x - 2

    x_start = -2.0
    x_end = 2.0
    num_points = 2 # x-values: -2, 2

    # Expected: (-2)^2-2 = 2, (2)^2-2 = 2
    expected_coordinates = [(-2.0, 2.0), (2.0, 2.0)] 

    result = GraphEvaluator.evaluate_expression_for_range(quadratic_func, x_start, x_end, num_points)

    assert len(result) == len(expected_coordinates)
    for i in range(len(result)):
        assert result[i][0] == pytest.approx(expected_coordinates[i][0], rel=1e-3)
        assert result[i][1] == pytest.approx(expected_coordinates[i][1], rel=1e-3)

def test_error_invalid_input_types():
    """
    Test that TypeError is raised for invalid input types (non-callable function, non-numeric start/end, non-integer num_points).
    """
    def dummy_func(x):
        return x

    # Test non-callable parsed_expression_func
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range("not a func", 0, 1, 2)
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(None, 0, 1, 2)

    # Test non-numeric x_start
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, "0", 1, 2)
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, None, 1, 2)

    # Test non-numeric x_end
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, "1", 2)
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, None, 2)

    # Test non-integer num_points
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, 1, "invalid")
    with pytest.raises(TypeError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, 1, 2.5)

def test_error_num_points_less_than_two():
    """
    Test that ValueError is raised for num_points less than 2.
    """
    def dummy_func(x):
        return x

    with pytest.raises(ValueError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, 1, 1) # num_points = 1

    with pytest.raises(ValueError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, 1, 0) # num_points = 0

    with pytest.raises(ValueError):
        GraphEvaluator.evaluate_expression_for_range(dummy_func, 0, 1, -5) # num_points = negative


# ============================================================================
# Tests for GraphEvaluator class
# ============================================================================

def test_graphevaluator_instantiation():
    """Test GraphEvaluator can be instantiated"""
    instance = GraphEvaluator()
    assert instance is not None


def test_graphevaluator_evaluate_expression_for_range(graphevaluator_instance):
    """Test GraphEvaluator.evaluate_expression_for_range()"""
    # TODO: Add test implementation
    pass



# ============================================================================
# Edge Case Tests
# ============================================================================

