"""
Tests for src/main.py

Auto-generated by TestGeneratorAgent
"""

import pytest
from unittest.mock import Mock, patch, MagicMock
from src.main import *



# ============================================================================
# Fixtures
# ============================================================================


# ============================================================================
# Tests for main()
# ============================================================================

import pytest
from unittest import mock
from src.main import main

# Mock the greeter module for isolated testing
@mock.patch('src.main.greet')
def test_main_prints_greeting_message(mock_greet, capsys):
    """
    Test that main() correctly calls greet() and prints its returned message.
    """
    expected_greeting = "Hello, Pytest World!"
    mock_greet.return_value = expected_greeting

    main()

    captured = capsys.readouterr()
    assert captured.out.strip() == expected_greeting
    mock_greet.assert_called_once()

@mock.patch('src.main.greet')
def test_main_handles_exception_from_greeter(mock_greet, capsys):
    """
    Test that main() catches and prints an error message if greet() raises an exception.
    """
    error_message = "Something went wrong in greet!"
    mock_greet.side_effect = Exception(error_message)

    main()

    captured = capsys.readouterr()
    assert f"An unexpected error occurred while generating the greeting: {error_message}" in captured.out
    mock_greet.assert_called_once()

@mock.patch('src.main.greet')
def test_main_handles_keyboard_interrupt(mock_greet, capsys):
    """
    Test that main() catches and prints a message if a KeyboardInterrupt occurs.
    """
    mock_greet.side_effect = KeyboardInterrupt("User aborted")

    main()

    captured = capsys.readouterr()
    assert "Application interrupted by user." in captured.out
    mock_greet.assert_called_once()

@mock.patch('src.main.greet')
def test_main_prints_empty_string_if_greeter_returns_empty(mock_greet, capsys):
    """
    Test that main() correctly handles and prints an empty string returned by greet().
    """
    mock_greet.return_value = ""

    main()

    captured = capsys.readouterr()
    assert captured.out.strip() == ""
    mock_greet.assert_called_once()


# ============================================================================
# Edge Case Tests
# ============================================================================

